const localization = {
    en: {
        translation: {
            'English': 'English',
            'Armenian': 'Հայերեն - Armenian',
            'Russian': 'Русский - Russian',
            'A': 'A',
            'B': 'B',
            'OK': 'OK',
            'Home': 'Home',
            'Settings': 'Settings',
            'Login': 'Login',
            'Logout': 'Logout',
            'Login_verb': 'Login',
            'Save': 'Save',
            'Account': 'Account',
            'Register': 'Register',
            'Register_verb': 'Register',
            'Next': 'Next',
            'Don\'t have an Account yet?': 'Don\'t have an Account yet?',
            'Already have an Account?': 'Already have an Account?',
            'Confirm': 'Confirm',
            'Login to app': 'Login to {{appName}}',
            'Register for': 'Register for {{appName}}',
            'Display Name': 'Display Name',
            'Email': 'Email',
            'Password': 'Password',
            'Current Password': 'Current Password',
            'New Password': 'New Password',
            'Confirm Password': 'Confirm Password',
            'Forgot Password?': 'Forgot Password?',
            'Request new password': 'Request new password',
            'Your password was successfully reset': 'Your password was successfully reset',
            'Google Login': 'Google Login',
            'Facebook Login': 'Facebook Login',
            'Language': 'Language',
            'Email is required': 'Email is required',
            'Invalid Email Address': 'Invalid Email Address',
            'Please enter the Password': 'Please enter the Password',
            'Please enter a Password': 'Please enter a Password',
            'Please enter a new Password': 'Please enter a new Password',
            'Please confirm the Password': 'Please confirm the Password',
            'Passwords do not match': 'Passwords do not match',
            'password-validation-error': 'Use at least 8 characters that include Latin lowercase, uppercase letters, and numbers.',
            'Wrong Password': 'Wrong Password',
            'Registration success': 'Registration success',
            'registration-success-body': 'You have successfully registered. Please check your email to verify your account. If you have not received the email you can request a new one',
            'registration-success-body-end1': ' in {{sec}} seconds.',
            'registration-success-body-end2': ' by clicking on the button below.',
            'Your account is not verified': 'Your account is not verified',
            'not-verified-body': 'You should have received account verification email after registration. If you have not received it or the link was expired you can request a new Email',
            'not-verified-body-end1': ' in {{sec}} seconds.',
            'not-verified-body-end2': ' by clicking on the button below.',
            'Resend Verification Email': 'Resend Verification Email',
            'Check your Email': 'Check your Email',
            'password-reset-success-body': 'The password reset link has been sent to your email address.',
            'Google Login Error:': 'Google Login Error:',
            'Email Verification': 'Email Verification',
            'email-verification-success': 'Dear {{displayName}}, your email address {{email}} has been successfully verified. You can login now.',
            'email-verification-success-only-email': 'Your email address {{email}} has been successfully verified. You can login now.',
            'Go to Login Page': 'Go to Login Page',
            'Unknown Error': 'Unknown Error',
            'An error occured': 'An error occured',
            'Manage Tournaments': 'Manage Tournaments',
            'Select Mode': 'Select Mode',
            'Tournament Settings': 'Tournament Settings',
            'Add Participants': 'Add Participants',
            'Create New Tournament': 'Create New Tournament',
            'Login to Create a Tournament': 'Login to Create a Tournament',
            'User Profile': 'User Profile',
            'ERROR_EmailInUseError': 'Email address already in use',
            'ERROR_EmailRequestSmallIntervalError': 'The interval between new email requests was too small, please try later',
            'ERROR_InvalidTokenError': 'Provided token is invalid',
            'ERROR_AlreadyVerifiedError': 'User is already verified',
            'ERROR_UserNotFoundError': 'User not found',
            'ERROR_WrongPasswordError': 'Wrong password',
            'ERROR_UserNotVerifiedError': 'User is not verified',
            'ERROR_Unauthorized': 'Unauthorized',
            'ERROR_ValidationError': 'Validation error',
            'ERROR_MailSendError': 'Error sending the Email',
            'ERROR_SocialUserForgotPasswordError': 'You can\'t reset your password since you were logged in via Google / Facebook',
            'Your Profile': 'Your Profile',
            'You are logged out': 'You are logged out',
            'Changes saved': 'Changes saved',
            'Round Robin': 'Round Robin',
            'Last Man Standing': 'Last Man Standing',
            'Elimination': 'Elimination',
            'Teams': 'Teams',
            'Single': 'Single',
            'Draw Your Partner': 'Draw Your Partner',
            'MonsterDYP': 'Monster DYP',
            'Number of Tables': 'Number of Tables',
            'Number of Lives': 'Number of Lives',
            'Quick Entry': 'Quick Entry',
            'Goals to Win': 'Goals to Win',
            'Draw': 'Draw',
            'Winning Sets': 'Winning Sets',
            'Sets': 'Sets',
            'Tables': 'Tables',
            'Table': 'Table',
            'Table_plural': 'Тables',
            'Life': '{{count}} Life',
            'Life_plural': '{{count}} Lives',
            'Goals': 'Goals',
            'Goal': 'Goal',
            'Goal_plural': 'Goals',
            'Semifinal': 'Semifinal',
            'Final': 'Final',
            'Final_plural': 'Finals',
            'Set': '{{count}} Set',
            'Set_plural': '{{count}} Sets',
            'Point': '{{count}} Point',
            'Point_plural': '{{count}} Points',
            'form-subheader-tables-text': 'Tables can be added or deactivated during the tournament.',
            'form-subheader-goals-text': 'If \'Quick Entry\' is selected, you can only choose the winning team or draw. This option can be changed before starting the elimination system. \'Goals for Win\' can be changed during the tournament.',
            'form-subheader-names-text': 'The order entered here, reflects the initial ranking in the table.',
            'form-subheader-names-dyp-text': 'A and B players will most likely end up in one team. So it is possible to add attributes to players, e.g. amateur and pro; offence and defence. It will be possible to edit the teams in the next step.',
            'form-subheader-lms-text': 'Player will lose a life with every lost match. A player without any lives left, will drop out.',
            'Names': 'Names',
            'Set Players': 'Set Players',
            'player-form-few-players': 'You need at least {{number}} players.',
            'player-form-duplicate-name': 'Name \'{{name}}\' already used!',
            'player-form-odd-players-error': 'You need an even number of players.',
            'player-import-form-duplicate-name': 'Name \'{{name}}\' is a duplicate.',
            'player-import-form-duplicate-names': 'Names \'{{names}}\' are duplicates.',
            'Create Elimination Bracket': 'Create Elimination Bracket',
            'Participant': 'Participant',
            '<Bye>': '<Bye>',
            'Cancel': 'Cancel',
            'Start Tournament': 'Start Tournament',
            'That is one good-looking Tournament!': 'That is one good-looking Tournament!',
            'Do you want to give it a name?': 'Do you want to give it a name?',
            'Tournament Name': 'Tournament Name',
            'Shuffle Participants': 'Shuffle Participants',
            'Shuffle Players': 'Shuffle Players',
            'Import Participants': 'Import Participants',
            'Import': 'Import',
            'Return to Previous Step': 'Return to Previous Step',
            'import-participants-dialog-description': 'Paste names of participants below. Names can be seperated by comma, semicolon or newline.',
            'Match for Third Place': 'Match for Third Place',
            'Third Place': 'Third Place',
            'Delete Account': 'Delete Account',
            'delete-account-confirmation-message': 'You are about to delete your user account, including all tournament data you have. If you are sure, confirm your action. You will receive an email with a link to delete your account.',
            'request-delete-account-success-message': 'Your request has been processed, please check your email.',
            'delete-account-success-message': 'Your account has been successfully deleted. Sorry you\'re leaving.',
            'vs': 'vs',
            'Enter Result': 'Enter Result',
            'less-than-winning-sets-message': 'One of the Players Should Have {{winningSets}} Wins According to the Number of Winning Sets.',
            'Full Screen': 'Full Screen',
            'Exit Full Screen': 'Exit Full Screen',
            'Remove Player': 'Remove Player',
            'Removed': 'Removed',
            'Assigned': 'Assigned',
            'Create Teams': 'Create Teams',
            'You need 2 players per team.': 'You need 2 players per team.',
            'Points': 'Points',
            'Points for Win': 'Points for Win',
            'Points for Draw': 'Points for Draw',
            'form-subheader-points-text': 'The "points for scarce matches" setting allows points to be awarded, to the loser of a game, that has a scarce goal difference. For multiple sets or disciplines, all goals of that match are added.',
            'select-both-scores-message': 'The score for both opponents must be selected.',
            'Round': 'Round {{round}}',
            'New Round': 'New Round',
            'Show Result': 'Show Result',
            'Show Standings': 'Show Standings',
            'Hide Standings': 'Hide Standings',
            'enter-score-hint-text': 'You can enter the scores by typing both numbers followed by the Enter key. Press Ctrl + Enter to confirm.',
            'LMSStatsCol_Player': 'Player',
            'LMSStatsCol_Lives': 'Lives',
            'LMSStatsCol_NumberOfGames': 'Num.',
            'LMSStatsCol_Points': 'Pts',
            'LMSStatsCol_Goals': 'G+',
            'LMSStatsCol_GoalsIn': 'G-',
            'LMSStatsCol_GoalDiff': 'G±',
            'Lives Left': 'Lives Left',
            'Goals In': 'Goals In',
            'Goal Difference': 'Goal Difference',
            'Match Count': 'Match Count',
            'Average Points': 'Average Points',
            'Player Name': 'Player Name',
            'Configure Table': 'Configure Table',
        }
    },
    hy: {
        translation: {
            'English': 'English - Անգլերեն',
            'Armenian': 'Հայերեն',
            'Russian': 'Русский - Ռուսերեն',
            'A': 'Ա',
            'B': 'Բ',
            'OK': 'Լավ',
            'Home': 'Սկիզբ',
            'Settings': 'Կարգավորումներ',
            'Login': 'Մուտք',
            'Logout': 'Ելք',
            'Login_verb': 'Մուտք գործեք',
            'Save': 'Պահպանել',
            'Account': 'Հաշիվ',
            'Register': 'Գրանցվել',
            'Register_verb': 'Գրանցվեք',
            'Next': 'Առաջ',
            'Don\'t have an Account yet?': 'Դեռ չունե՞ք հաշիվ։',
            'Already have an Account?': 'Արդեն գրանցվա՞ծ եք։',
            'Confirm': 'Հաստատել',
            'Login to app': 'Մուտք {{appName}}',
            'Register for': 'Գրանցվեք {{appName}}-ում',
            'Display Name': 'Անուն',
            'Email': 'Էլ. փոստ',
            'Password': 'Գաղտնաբառ',
            'Current Password': 'Ընթացիկ գաաղտնաբառ',
            'New Password': 'Նոր գաղտնաբառ',
            'Confirm Password': 'Հաստատեք գաղտնաբառը',
            'Forgot Password?': 'Մոռացե՞լ եք գաղտնաբառը',
            'Request new password': 'Վերակայել գաղտնաբառը',
            'Your password was successfully reset': 'Գաղտնաբառը հաջողությամբ վերակայված է',
            'Google Login': 'Մուտք Google-ով',
            'Facebook Login': 'Մուտք Facebook-ով',
            'Language': 'Լեզու',
            'Email is required': 'Էլ. փոստը պարտադիր է',
            'Invalid Email Address': 'Անվավեր էլ. փոստի հասցե',
            'Please enter the Password': 'Մուտքագրեք գաղտնաբառը',
            'Please enter a Password': 'Մուտքագրեք գաղտնաբառ',
            'Please enter a new Password': 'Մուտքագրեք նոր գաղտնաբառ',
            'Please confirm the Password': 'Կրկնեք գաղտնաբառը',
            'Passwords do not match': 'Գաղնտաբառերը չեն համընկնում',
            'password-validation-error': 'Գաղտնաբառը պետք է կազմված լինի առնվազն 8 նիշից և պարունակի լատինական այբուբենի մեծատառեր, փոքրատառեր և թվեր։',
            'Wrong Password': 'Գաղտնաբառը սխալ է',
            'Registration success': 'Գրանցումը հաջողվեց',
            'registration-success-body': 'Դուք հաջողությամբ գրանցվել եք։ Խնդրում ենք ստուգել Ձեր էլ. փոստը, որպեսզի հաստատեք Ձեր հաշիվը։ Եթե նամակ չեք ստացել, կարող եք նորը ստանալու հարցում կատարել',
            'registration-success-body-end1': ' {{sec}} վայրկյանից։',
            'registration-success-body-end2': '՝ սեղմելով կոճակը ստորև։',
            'Your account is not verified': 'Ձեր հաշիվը հաստատված չէ',
            'not-verified-body': 'Գրանցվելուց հետո Դուք պետք է որ ստացած լինեք հաշվի հաստատման նամակ։ Եթե այն չեք ստացել կամ հաստատման հղումը ժամկետնանց է, կարող եք նորը ստանալու հարցում կատարել',
            'not-verified-body-end1': ' {{sec}} վայրկյանից։',
            'not-verified-body-end2': '՝ սեղմելով կոճակը ստորև։',
            'Resend Verification Email': 'Նորից ուղարկել հաստատման նամակը',
            'Check your Email': 'Ստուգեք Ձեր էլ. փոստը',
            'password-reset-success-body': 'Գաղտնաբառի վերակայման հղումն ուղարկվել է Ձեր էլ. փոստի հասցեին։',
            'Google Login Error:': 'Google մուտքի սխալ.',
            'Email Verification': 'Էլ. փոստի հաստատում',
            'email-verification-success': 'Հարգելի {{displayName}}, Ձեր էլ. փոստի {{email}} հասցեն հաջողությամբ հաստատվել է։ Այժմ կարող եք մուտք գործել։',
            'email-verification-success-only-email': 'Ձեր էլ. փոստի {{email}} հասցեն հաջողությամբ հաստատվել է։ Այժմ կարող եք մուտք գործել։',
            'Go to Login Page': 'Դեպի մուտքի էջ',
            'Unknown Error': 'Անծանոթ սխալ',
            'An error occured': 'Տեղի ունեցավ սխալ',
            'Manage Tournaments': 'Մրցաշարերի կառավարում',
            'Select Mode': 'Ընտրեք տեսակը',
            'Tournament Settings': 'Մրցաշարի կարգավորումներ',
            'Add Participants': 'Ավելացրեք մասնակիցներ',
            'Create New Tournament': 'Ստեղծել նոր մրցաշար',
            'Login to Create a Tournament': 'Մուտք գործեք՝ մրցաշար ստեղծելու համար',
            'User Profile': 'Օգտվողի հաշիվ',
            'ERROR_EmailInUseError': 'Էլ. փոստի հաստեն արդեն զբաղված է',
            'ERROR_EmailRequestSmallIntervalError': 'Նոր նամակի ստացման հարցումների միջև տևողությունը շատ կարճ է, փորձեք ավելի ուշ',
            'ERROR_InvalidTokenError': 'Տրամադրված բանալին անվավեր է',
            'ERROR_AlreadyVerifiedError': 'Օգտվողն արդեն հաստատված է',
            'ERROR_UserNotFoundError': 'Օգտվողը չի գտնվել',
            'ERROR_WrongPasswordError': 'Գաղտնաբառը սխալ է',
            'ERROR_UserNotVerifiedError': 'Օգտվողը հաստատված չէ',
            'ERROR_Unauthorized': 'Չլիազորված հարցում',
            'ERROR_ValidationError': 'Վավերացման սխալ',
            'ERROR_MailSendError': 'Նամակի ուղարկման սխալ',
            'ERROR_SocialUserForgotPasswordError': 'Դուք չեք կարող վերակայել գաղտնաբառը, քանի որ նախկինում մուտք եք գործել Google / Facebook հաշվով',
            'Your Profile': 'Ձեր հաշիվը',
            'You are logged out': 'Դուք մուտք գործած չեք',
            'Changes saved': 'Փոփոխությունները պահպանված են',
            'Round Robin': 'Բոլորը բոլորի դեմ',
            'Last Man Standing': 'Վերջին հերոս (LMS)',
            'Elimination': 'Փլեյ-օֆֆ',
            'Teams': 'Թիմեր',
            'Single': 'Անհատական',
            'Draw Your Partner': 'Ընտրիր քո թիմակցին',
            'MonsterDYP': 'Monster DYP',
            'Number of Tables': 'Սեղանների քանակ',
            'Number of Lives': 'Կյանքերի քանակ',
            'Quick Entry': 'Արագ մուտք',
            'Goals to Win': 'Գոլեր հաղթանակի համար',
            'Draw': 'Ոչ ոքի',
            'Winning Sets': 'Սեթեր հաղթանակի համար',
            'Sets': 'Սեթեր',
            'Table': 'սեղան',
            'Tables': 'Սեղաններ',
            'Life': '{{count}} կյանք',
            'Life_plural': '{{count}} կյանք',
            'Table_plural': 'սեղան',
            'Goals': 'Գոլեր',
            'Goal': 'գոլ',
            'Goal_plural': 'գոլ',
            'Semifinal': 'Կիսաեզրափակիչ',
            'Final': 'Եզրափակիչ',
            'Final_plural': 'Եզրափակիչ',
            'Set': '{{count}} սեթ',
            'Set_plural': '{{count}} սեթ',
            'Point': '{{count}} միավոր',
            'Point_plural': '{{count}} միավոր',
            'form-subheader-tables-text': 'Սեղանները կարող են ակտիվացվել կամ ապաակտիվացվել մրցաշարի ընթացքում։',
            'form-subheader-goals-text': 'Եթե ընտրված է «Արագ մուտք», հնարավոր է ընտրել միայն հաղթող թիմին կամ Ոչ ոքի։ Այս ընտրանքը կարող է փոխվել մինչ հեռացման մեկնարկը։ «Գոլեր հաղթանակի համար» ընտրանքը հնարավոր է փոխել մրցաշարի ընթացքում։',
            'form-subheader-names-text': 'Այստեղ մուտքագրված հերթականությունը կանդրադառնա աղյուսակում սկզբնական դասավորության վրա։',
            'form-subheader-names-dyp-text': 'Ա և Բ խաղացողներն ամենայն հավանականությամբ կհայտնվեն միևնույն թիմում։ Այսպիսով՝ հնարավոր է խաղացողներին տալ հատկանիշներ, օր.՝ պրոֆեսիոնալ և սիրողական խաղացող, կամ հարձակվող և պաշտպան։ Հաջորդ քայլին հնարավոր կլինի խմբագրել թիմերը։',
            'form-subheader-lms-text': 'Խաղացողը կկորցնի մեկ կյանք ամեն պարտված խաղի համար։ Կյանքերի սպառվելու դեպքում խաղացողը դուրս կմնա մրցապայքարից։',
            'Names': 'Անուններ',
            'Set Players': 'Ընտրել խմբեր',
            'player-form-few-players': 'Անհրաժեշտ է առնվազն {{number}} խաղացող։',
            'player-form-duplicate-name': '«{{name}}» անունն արդեն օգտագործվել է։',
            'player-form-odd-players-error': 'Դուք պետք է ունենաք զույգ թվով խաղացողներ։',
            'player-import-form-duplicate-name': '«{{name}}» անունը կրկնվում է։',
            'player-import-form-duplicate-names': '«{{names}}» անունները կրկնվում են։',
            'Create Elimination Bracket': 'Ստեղծեք փլեյ-օֆֆ մրցաշարը',
            'Participant': 'Մասնակից',
            '<Bye>': '<Դատարկ>',
            'Cancel': 'Չեղարկել',
            'Start Tournament': 'Սկսել մրցաշարը',
            'That is one good-looking Tournament!': 'Մրցաշարը պատրաստ է ստեղծման։',
            'Do you want to give it a name?': 'Ցանկանո՞ւմ եք անուն դնել դրան։',
            'Tournament Name': 'Մրցաշարի անուն',
            'Shuffle Participants': 'Խառնել մասնակիցներին',
            'Shuffle Players': 'Խառնել խաղացողներին',
            'Import Participants': 'Ներկրել մասնակիցներ',
            'Import': 'Ներկրել',
            'Return to Previous Step': 'Վերադառնալ նախորդ քայլին',
            'import-participants-dialog-description': 'Փակցրեք մասնակիցների անունները ստորև։ Անունները կարող են տարանջատված լինել ստորակետով, կետ-ստորակետով կամ նոր տողով։',
            'Match for Third Place': 'Խաղ երրորդ տեղի համար',
            'Third Place': 'Երրորդ տեղ',
            'Delete Account': 'Ջնջել հաշիվը',
            'delete-account-confirmation-message': 'Դուք պատրաստվում եք ջնջել Ձեր հաշիվը, ներառյալ Ձեր բոլոր մրցաշարերի տվյալները։ Եթե համոզված եք, հաստատեք Ձեր գործողությունը։ Դուք կստանաք հաշվի ջնջման հղումով նամակ Ձեր էլ. փոստին։',
            'request-delete-account-success-message': 'Ձեր դիմումն ընդունված է, խնդրում ենք ստուգել Ձեր էլ. փոստը։',
            'delete-account-success-message': 'Ձեր հաշիվը հաջողությամբ ջնջված է։ Ցավում ենք, որ հեռանում եք։',
            'vs': 'ընդ.',
            'Enter Result': 'Մուտքագրել արդյունքը',
            'less-than-winning-sets-message': 'Խաղացողներից մեկնումեկը պետք է ունենա {{winningSets}} հաղթանակ՝ ըստ հաղթանակի սեթերի քանակի։',
            'Full Screen': 'Լիաէկրան ռեժիմ',
            'Exit Full Screen': 'Ելք լիաէկրան ռեժիմից',
            'Remove Player': 'Հեռացնել խաղացողին',
            'Removed': 'Չնշանակված',
            'Assigned': 'Նշանակված',
            'Create Teams': 'Ստեղծեք թիմերը',
            'You need 2 players per team.': 'Թիմերը պետք է ունենան 2 խաղացող։',
            'Points': 'Միավորներ',
            'Points for Win': 'Միավորներ հաղթանակի համար',
            'Points for Draw': 'Միավորներ ոչ ոքիի համար',
            'form-subheader-points-text': 'The "points for scarce matches" setting allows points to be awarded, to the loser of a game, that has a scarce goal difference. For multiple sets or disciplines, all goals of that match are added.',
            'select-both-scores-message': 'Երկու հակառակորդի հաշիվն էլ պետք է նշված լինի։',
            'Round': 'Փուլ {{round}}',
            'New Round': 'Նոր փուլ',
            'Show Result': 'Ցուցադրել արդյունքը',
            'Show Standings': 'Ցույց տալ մրցաշարային աղյուսակը',
            'Hide Standings': 'Թաքցնել մրցաշարային աղյուսակը',
            'enter-score-hint-text': 'Դուք կարող եք նշել հաշիվը ստեղնաշարով՝ մուտքագրելով միավորն ու սեղմելով Enter յուրաքանչյուրից հետո։ Սեղմեք Ctrl + Enter հաստատելու համար։',
            'LMSStatsCol_Player': 'Մասնակից',
            'LMSStatsCol_Lives': 'Կյանք',
            'LMSStatsCol_NumberOfGames': 'Խաղ',
            'LMSStatsCol_Points': 'Մվր',
            'LMSStatsCol_Goals': 'Գ+',
            'LMSStatsCol_GoalsIn': 'Գ-',
            'LMSStatsCol_GoalDiff': 'Գ±',
            'Lives Left': 'Մնացած կյանքեր',
            'Goals In': 'Ընդունած գնդակներ',
            'Goal Difference': 'Գոլերի տարբերություն',
            'Match Count': 'Խաղերի քանակ',
            'Average Points': 'Միջին միավորներ',
            'Player Name': 'Մասնակցի անուն',
            'Configure Table': 'Խմբագրել աղյուսակը',
        }
    },
    ru: {
        translation: {
            'English': 'English - Английский',
            'Armenian': 'Հայերեն - Армянский',
            'Russian': 'Русский',
            'A': 'А',
            'B': 'Б',
            'OK': 'OK',
            'Home': 'Домой',
            'Settings': 'Настройки',
            'Login': 'Вход',
            'Logout': 'Выход',
            'Login_verb': 'Входите',
            'Save': 'Сохранить',
            'Account': 'Учётная запись',
            'Register': 'Регистрироваться',
            'Register_verb': 'Регистрируйтесь',
            'Next': 'Продолжить',
            'Don\'t have an Account yet?': 'У вас нет учётной записи?',
            'Already have an Account?': 'Уже есть учетная запись?',
            'Confirm': 'Подтвердить',
            'Login to app': 'Войти в {{appName}}',
            'Register for': 'Зарегистрироваться на {{appName}}',
            'Display Name': 'Имя',
            'Email': 'Почта',
            'Password': 'Пароль',
            'Current Password': 'Текущий пароль',
            'New Password': 'Новый пароль',
            'Confirm Password': 'Подтвердите Пароль',
            'Forgot Password?': 'Забыли пароль?',
            'Your password was successfully reset': 'Ваш пароль был успешно сброшен',
            'Request new password': 'Сбросить пароль',
            'Google Login': 'Вход через Google',
            'Facebook Login': 'Вход через Facebook',
            'Language': 'Язык',
            'Email is required': 'Электронная почта обязательна',
            'Invalid Email Address': 'Неверный адрес электронной почты',
            'Please enter the Password': 'Введите пароль',
            'Please enter a Password': 'Введите пароль',
            'Please enter a new Password': 'Введите новый пароль',
            'Please confirm the Password': 'Повторно введите пароль',
            'Passwords do not match': 'Пароли не совпадают',
            'Wrong Password': 'Неверный пароль',
            'Registration success': 'Вы успешно зарегистрировались',
            'registration-success-body': 'Вы успешно зарегистрировались. Пожалуйста, проверьте свою электронную почту, чтобы подтвердить свою учетную запись. Если вы не получили письмо, вы можете запросить новое',
            'registration-success-body-end1': ' через {{sec}} сек.',
            'registration-success-body-end2': ' нажимая кнопку ниже.',
            'Your account is not verified': 'Ваша учетная запись не подтверждена',
            'not-verified-body': 'После регистрации вы должны были получить электронное письмо для подтверждения учетной записи. Если вы не получили его или срок действия ссылки истек, вы можете запросить новое письмо',
            'not-verified-body-end1': ' через {{sec}} сек.',
            'not-verified-body-end2': ' нажимая кнопку ниже.',
            'Resend Verification Email': 'Выслать повторно письмо для подтверждения',
            'Check your Email': 'Праверьте вашу почту',
            'password-reset-success-body': 'Ссылка для сброса пароля была отправлена на ваш адрес электронной почты.',
            'Google Login Error:': 'Ошибка входа Google:',
            'Email Verification': 'Подтверждение электронной почты',
            'email-verification-success': 'Уважаемый {{displayName}}, ваш адрес электронной почты {{email}} успешно подтвержден. Можете войти.',
            'email-verification-success-only-email': 'Ваш адрес электронной почты {{email}} успешно подтвержден. Можете войти.',
            'Go to Login Page': 'На страницу входа',
            'Unknown Error': 'Произошла ошибка',
            'An error occured': 'An error occured',
            'Manage Tournaments': 'Управление турнирами',
            'Select Mode': 'Выберите режим',
            'Tournament Settings': 'Настройки турнира',
            'Add Participants': 'Добавьте участников',
            'Create New Tournament': 'Создать новый турнир',
            'Login to Create a Tournament': 'Войдите, чтобы создать турнир',
            'User Profile': 'Профиль',
            'ERROR_EmailInUseError': 'Адрес электронной почты уже используется',
            'ERROR_EmailRequestSmallIntervalError': 'Интервал между новыми запросами электронной почты был слишком мал, попробуйте позже',
            'ERROR_InvalidTokenError': 'Предоставленный токен недействителен',
            'ERROR_AlreadyVerifiedError': 'Пользователь уже подтвержден',
            'ERROR_UserNotFoundError': 'Пользователь не найден',
            'ERROR_WrongPasswordError': 'Неверный пароль',
            'ERROR_UserNotVerifiedError': 'Пользователь не подтвержден',
            'ERROR_Unauthorized': 'Неавторизованный запрос',
            'ERROR_ValidationError': 'Ошибка валидации',
            'ERROR_MailSendError': 'Ошибка при отправке письма',
            'ERROR_SocialUserForgotPasswordError': 'Вы не можете сбросить пароль, так как вы вошли в систему через Google / Facebook',
            'Your Profile': 'Ваш профиль',
            'You are logged out': 'Вы вышли из системы',
            'Changes saved': 'Изменения сохранены',
            'Round Robin': 'Все со всеми',
            'Last Man Standing': 'Последний выживший (LMS)',
            'Elimination': 'На вылет',
            'Teams': 'Команды',
            'Single': 'Одиночные',
            'Draw Your Partner': 'Выберите своего партнера',
            'MonsterDYP': 'Monster DYP',
            'Number of Tables': 'Количество столов',
            'Number of Lives': 'Количество жизней',
            'Quick Entry': 'Быстрый вход',
            'Goals to Win': 'Голы для победы',
            'Draw': 'Ничья',
            'Winning Sets': 'Сеты для победы',
            'Sets': 'Сеты',
            'Tables': 'Столы',
            'Table': 'стол',
            'Table_plural': 'столов',
            'Table_1': 'стола',
            'Table_2': 'столов',
            'Life': '{{count}} жизнь',
            'Life_plural': '{{count}} жизней',
            'Life_1': '{{count}} жизни',
            'Life_2': '{{count}} жизней',
            'Goals': 'Голы',
            'Goal': 'гол',
            'Goal_plural': 'голов',
            'Semifinal': 'Полуфинал',
            'Final': 'Финал',
            'Final_plural': 'Финал',
            'Goal_1': 'гола',
            'Goal_2': 'голов',
            'Set': '{{count}} сет',
            'Set_plural': '{{count}} сетов',
            'Set_1': '{{count}} сета',
            'Set_2': '{{count}} сетов',
            'Point': '{{count}} очко',
            'Point_plural': '{{count}} очков',
            'Point_1': '{{count}} очка',
            'Point_2': '{{count}} очков',
            'form-subheader-tables-text': 'Столы можно добавлять или удалять во время турнира.',
            'form-subheader-goals-text': 'Если выбран «Быстрый вход», вы можете выбрать только победившую команду или ничью. Этот параметр можно изменить перед запуском системы исключения. «Голы на победу» можно менять во время турнира.',
            'form-subheader-names-text': 'Очередность заданная здесь отразиться на первоначальном расположении в таблице.',
            'form-subheader-names-dyp-text': 'Игроки А и Б, скорее всего, попадут в одну команду. Таким образом, игрокам можно добавлять атрибуты, например любитель и профи; нападение и защита. На следующем шаге можно будет редактировать команды.',
            'form-subheader-lms-text': 'Игроки теряют одну жизнь с каждым проигранным матчем. Игрок, у которого не осталось жизней выбывает.',
            'Names': 'Имена',
            'Set Players': 'Выбрать группы игроков',
            'player-form-few-players': 'Минимум {{number}} игрока',
            'player-form-duplicate-name': 'Имя "{{name}}" уже используется!',
            'player-form-odd-players-error': 'Вам нужно четное количество игроков.',
            'player-import-form-duplicate-name': 'Имя "{{name}}" повторяется.',
            'player-import-form-duplicate-names': 'Имена "{{names}}" повторяются.',
            'Create Elimination Bracket': 'Создайте сетку на выбывание',
            'Participant': 'Участник',
            '<Bye>': '<Фрислот>',
            'Cancel': 'Отмена',
            'Start Tournament': 'Начать турнир',
            'That is one good-looking Tournament!': 'Это турнир выглядит круто!',
            'Do you want to give it a name?': 'Хотите его как-нибудь назвать?',
            'Tournament Name': 'Имя турнира',
            'Shuffle Participants': 'Пепемешать участников',
            'Shuffle Players': 'Пепемешать игроков',
            'Import Participants': 'Импортировать участников',
            'Import': 'Импортировать',
            'Return to Previous Step': 'Вернуться на предыдущий шаг',
            'import-participants-dialog-description': 'Вставьте имена участников ниже. Имена могут быть разделены запятой, точкой с запятой или новой строкой.',
            'Match for Third Place': 'Матч за третье место',
            'Third Place': 'Третье место',
            'Delete Account': 'Удалить учетную запись',
            'delete-account-confirmation-message': 'Вы собираетесь удалить свою учетную запись, включая все данные о турнирах. Если вы уверены, подтвердите свое действие. Вы получите электронное письмо со ссылкой для удаления учетной записи.',
            'request-delete-account-success-message': 'Ваш запрос обработан, проверьте вашу электронную почту.',
            'delete-account-success-message': 'Ваша учетная запись была успешно удалена. Нам жаль, что вы уходите.',
            'vs': 'X',
            'Enter Result': 'Вводить счет',
            'less-than-winning-sets-message': 'Один из игроков должен иметь {{winningSets}} выигрышей согласно количеству сетов для победы.',
            'Full Screen': 'Полный экран',
            'Exit Full Screen': 'Выход из полноэкранного режима',
            'Remove Player': 'Снять игрока',
            'Removed': 'Не назначенные',
            'Assigned': 'Назначенные',
            'Create Teams': 'Создать команды',
            'You need 2 players per team.': 'Вам нужно 2 игрока на команду.',
            'Points': 'Очки',
            'Points for Win': 'Очки за победу',
            'Points for Draw': 'Очки за ничью',
            'form-subheader-points-text': 'The "points for scarce matches" setting allows points to be awarded, to the loser of a game, that has a scarce goal difference. For multiple sets or disciplines, all goals of that match are added.',
            'select-both-scores-message': 'Необходимо выбрать счет для обоих соперников.',
            'Round': 'Раунд {{round}}',
            'New Round': 'Новый раунд',
            'Show Result': 'Показать результат',
            'Show Standings': 'Показать турнирную таблицу',
            'Hide Standings': 'Скрыть турнирную таблицу',
            'enter-score-hint-text': 'Вы можете ввести очки, набрав оба числа и нажав клавишу Enter после каждого. Нажмите Ctrl + Enter для подтверждения.',
            'LMSStatsCol_Player': 'Игрок',
            'LMSStatsCol_Lives': 'Жизни',
            'LMSStatsCol_NumberOfGames': 'Игр.',
            'LMSStatsCol_Points': 'Очки',
            'LMSStatsCol_Goals': 'Г+',
            'LMSStatsCol_GoalsIn': 'Г-',
            'LMSStatsCol_GoalDiff': 'Г±',
            'Lives Left': 'Оставшиеся жизни',
            'Goals In': 'Принятые голы',
            'Goal Difference': 'Разница голов',
            'Match Count': 'Количество игр',
            'Average Points': 'Average Points',
            'Player Name': 'Имя игрока',
            'Configure Table': 'Редактировать таблицу',
        }
    }
}

export default localization;