const localization = {
    en: {
        translation: {
            'English': 'English',
            'Armenian': 'Հայերեն - Armenian',
            'Russian': 'Русский - Russian',
            'Home': 'Home',
            'Settings': 'Settings',
            'Login': 'Login',
            'Logout': 'Logout',
            'Login_verb': 'Login',
            'Save': 'Save',
            'Account': 'Account',
            'Register': 'Register',
            'Register_verb': 'Register',
            'Next': 'Next',
            'Don\'t have an Account yet?': 'Don\'t have an Account yet?',
            'Already have an Account?': 'Already have an Account?',
            'Confirm': 'Confirm',
            'Login to app': 'Login to {{appName}}',
            'Register for': 'Register for {{appName}}',
            'Display Name': 'Display Name',
            'Email': 'Email',
            'Password': 'Password',
            'Current Password': 'Current Password',
            'New Password': 'New Password',
            'Confirm Password': 'Confirm Password',
            'Forgot Password?': 'Forgot Password?',
            'Request new password': 'Request new password',
            'Google Login': 'Google Login',
            'Facebook Login': 'Facebook Login',
            'Language': 'Language',
            'Email is required': 'Email is required',
            'Invalid Email Address': 'Invalid Email Address',
            'Please enter the Password': 'Please enter the Password',
            'Please enter a Password': 'Please enter a Password',
            'Please enter a new Password': 'Please enter a new Password',
            'Please confirm the Password': 'Please confirm the Password',
            'Passwords do not match': 'Passwords do not match',
            'password-validation-error': 'Use at least 8 characters that include Latin lowercase, uppercase letters, and numbers.',
            'Wrong Password': 'Wrong Password',
            'Registration success': 'Registration success',
            'registration-success-body': 'You have successfully registered. Please check your email to verify your account. If you have not received the email you can request a new one',
            'registration-success-body-end1': ' in {{sec}} seconds.',
            'registration-success-body-end2': ' by clicking on the button below.',
            'Resend Verification Email': 'Resend Verification Email',
            'Check your Email': 'Check your Email',
            'password-reset-success-body': 'The password reset link has been sent to your email address.',
            'Google Login Error:': 'Google Login Error:',
            'Email Verification': 'Email Verification',
            'email-verification-success': 'Dear {{displayName}}, your email address {{email}} has been successfully verified. You can login now.',
            'email-verification-success-only-email': 'Your email address {{email}} has been successfully verified. You can login now.',
            'Go to Login Page': 'Go to Login Page',
            'Unknown Error': 'Unknown Error',
            'Manage Tournaments': 'Manage Tournaments',
            'Select Mode': 'Select Mode',
            'Tournament Settings': 'Tournament Settings',
            'Add Participants': 'Add Participants',
            'Create New Tournament': 'Create New Tournament',
            'Login to Create a Tournament': 'Login to Create a Tournament',
            'User Profile': 'User Profile',
            'ERROR_EmailInUseError': 'Email address already in use',
            'ERROR_EmailRequestSmallIntervalError': 'The interval between new email requests was too small, please try later',
            'ERROR_InvalidTokenError': 'Provided token is invalid',
            'ERROR_AlreadyVerifiedError': 'User is already verified',
            'ERROR_UserNotFoundError': 'User not found',
            'ERROR_WrongPasswordError': 'Wrong password',
            'ERROR_UserNotVerifiedError': 'User is not verified',
            'ERROR_ValidationError': 'Validation error',
            'ERROR_MailSendError': 'Error sending the Email',
            'ERROR_SocialUserForgotPasswordError': 'You can\'t reset your password since you were logged in via Google / Facebook',
            'Your Profile': 'Your Profile',
            'You are logged out': 'You are logged out',
            'Changes saved': 'Changes saved',
            'Round Robin': 'Round Robin',
            'Last Man Standing': 'Last Man Standing',
            'Elimination': 'Elimination',
            'Teams': 'Teams',
            'Single': 'Single',
            'Draw Your Partner': 'Draw Your Partner',
            'Number of Tables': 'Number of Tables',
            'Quick Entry': 'Quick Entry',
            'Goals to Win': 'Goals to Win',
            'Draw': 'Draw',
            'Winning Sets': 'Winning Sets',
            'Tables': 'Tables',
            'Table': 'Table',
            'Table_plural': 'Тables',
            'Goals': 'Goals',
            'Goal': 'Goal',
            'Goal_plural': 'Goals',
            'Set': '{{count}} Set',
            'Set_plural': '{{count}} Sets',            
            'form-subheader-tables-text': 'Tables can be added or deactivated during the tournament.',
            'form-subheader-goals-text': 'If \'Quick Entry\' is selected, you can only choose the winning team or draw. This option can be changed before starting the elimination system. \'Goals for Win\' can be changed during the tournament.',
            'form-subheader-names-text':'The order entered here, reflects the initial ranking in the table.',
            'Names': 'Names',
            'player-form-duplicate-name': 'Name \'{{name}}\' already used!'
        }
    },
    hy: {
        translation: {
            'English': 'English - Անգլերեն',
            'Armenian': 'Հայերեն',
            'Russian': 'Русский - Ռուսերեն',
            'Home': 'Սկիզբ',
            'Settings': 'Կարգավորումներ',
            'Login': 'Մուտք',
            'Logout': 'Ելք',
            'Login_verb': 'Մուտք գործեք',
            'Save': 'Պահպանել',
            'Account': 'Հաշիվ',
            'Register': 'Գրանցվել',
            'Register_verb': 'Գրանցվեք',
            'Next': 'Առաջ',
            'Don\'t have an Account yet?': 'Դեռ չունե՞ք հաշիվ։',
            'Already have an Account?': 'Արդեն գրանցվա՞ծ եք։',
            'Confirm': 'Հաստատել',
            'Login to app': 'Մուտք {{appName}}',
            'Register for': 'Գրանցվեք {{appName}}-ում',
            'Display Name': 'Անուն',
            'Email': 'Էլ. փոստ',
            'Password': 'Գաղտնաբառ',
            'Current Password': 'Ընթացիկ գաաղտնաբառ',
            'New Password': 'Նոր գաղտնաբառ',
            'Confirm Password': 'Հաստատեք գաղտնաբառը',
            'Forgot Password?': 'Մոռացե՞լ եք գաղտնաբառը',
            'Request new password': 'Վերակայել գաղտնաբառը',
            'Google Login': 'Մուտք Google-ով',
            'Facebook Login': 'Մուտք Facebook-ով',
            'Language': 'Լեզու',
            'Email is required': 'Էլ. փոստը պարտադիր է',
            'Invalid Email Address': 'Անվավեր էլ. փոստի հասցե',
            'Please enter the Password': 'Մուտքագրեք գաղտնաբառը',
            'Please enter a Password': 'Մուտքագրեք գաղտնաբառ',
            'Please enter a new Password': 'Մուտքագրեք նոր գաղտնաբառ',
            'Please confirm the Password': 'Կրկնեք գաղտնաբառը',
            'Passwords do not match': 'Գաղնտաբառերը չեն համընկնում',
            'password-validation-error': 'Գաղտնաբառը պետք է կազմված լինի առնվազն 8 նիշից և պարունակի լատինական այբուբենի մեծատառեր, փոքրատառեր և թվեր։',
            'Wrong Password': 'Գաղտնաբառը սխալ է',
            'Registration success': 'Գրանցումը հաջողվեց',
            'registration-success-body': 'Դուք հաջողությամբ գրանցվել եք։ Խնդրում ենք ստուգել Ձեր էլ. փոստը, որպեսզի հաստատեք Ձեր հաշիվը։ Եթե նամակ չեք ստացել, կարող եք նորը ստանալու հարցում կատարել',
            'registration-success-body-end1': ' {{sec}} վայրկյանից։',
            'registration-success-body-end2': '՝ սեղմելով կոճակը ստորև։',
            'Resend Verification Email': 'Նորից ուղարկել հաստատման նամակը',
            'Check your Email': 'Ստուգեք Ձեր էլ. փոստը',
            'password-reset-success-body': 'Գաղտնաբառի վերակայման հղումն ուղարկվել է Ձեր էլ. փոստի հասցեին։',
            'Google Login Error:': 'Google մուտքի սխալ.',
            'Email Verification': 'Էլ. փոստի հաստատում',
            'email-verification-success': 'Հարգելի {{displayName}}, Ձեր էլ. փոստի {{email}} հասցեն հաջողությամբ հաստատվել է։ Այժմ կարող եք մուտք գործել։',
            'email-verification-success-only-email': 'Ձեր էլ. փոստի {{email}} հասցեն հաջողությամբ հաստատվել է։ Այժմ կարող եք մուտք գործել։',
            'Go to Login Page': 'Դեպի մուտքի էջ',
            'Unknown Error': 'Անծանոթ սխալ',
            'Manage Tournaments': 'Մրցաշարերի կառավարում',
            'Select Mode': 'Ընտրեք տեսակը',
            'Tournament Settings': 'Մրցաշարի կարգավորումներ',
            'Add Participants': 'Ավելացրեք մասնակիցներ',
            'Create New Tournament': 'Ստեղծել նոր մրցաշար',
            'Login to Create a Tournament': 'Մուտք գործեք՝ մրցաշար ստեղծելու համար',
            'User Profile': 'Օգտվողի հաշիվ',
            'ERROR_EmailInUseError': 'Էլ. փոստի հաստեն արդեն զբաղված է',
            'ERROR_EmailRequestSmallIntervalError': 'Նոր նամակի ստացման հարցումների միջև տևողությունը շատ կարճ է, փորձեք ավելի ուշ',
            'ERROR_InvalidTokenError': 'Տրամադրված բանալին անվավեր է',
            'ERROR_AlreadyVerifiedError': 'Օգտվողն արդեն հաստատված է',
            'ERROR_UserNotFoundError': 'Օգտվողը չի գտնվել',
            'ERROR_WrongPasswordError': 'Գաղտնաբառը սխալ է',
            'ERROR_UserNotVerifiedError': 'Օգտվողը հաստատված չէ',
            'ERROR_ValidationError': 'Վավերացման սխալ',
            'ERROR_MailSendError': 'Նամակի ուղարկման սխալ',
            'ERROR_SocialUserForgotPasswordError': 'Դուք չեք կարող վերակայել գաղտնաբառը, քանի որ նախկինում մուտք եք գործել Google / Facebook հաշվով',
            'Your Profile': 'Ձեր հաշիվը',
            'You are logged out': 'Դուք մուտք գործած չեք',
            'Changes saved': 'Փոփոխությունները պահպանված են',            
            'Round Robin': 'Բոլորը բոլորի դեմ',
            'Last Man Standing': 'Վերջին հերոս (LMS)',
            'Elimination': 'Հեռացում',
            'Teams': 'Թիմեր',
            'Single': 'Անհատական',
            'Draw Your Partner': 'Ընտրեք ձեր թիմակցին',
            'Number of Tables': 'Սեղանների քանակ',
            'Quick Entry': 'Արագ մուտք',
            'Goals to Win': 'Գոլեր հաղթանակի համար',
            'Draw': 'Ոչ ոքի',
            'Winning Sets': 'Սեթեր հաղթանակի համար',
            'Table': 'սեղան',
            'Tables': 'Սեղաններ',
            'Table_plural': 'սեղան',
            'Goals': 'Գոլեր',
            'Goal': 'գոլ',
            'Goal_plural': 'գոլ',
            'Set': '{{count}} սեթ',
            'Set_plural': '{{count}} սեթ',
            'form-subheader-tables-text': 'Սեղանները կարող են ակտիվացվել կամ ապաակտիվացվել մրցաշարի ընթացքում։',
            'form-subheader-goals-text': 'Եթե ընտրված է «Արագ մուտք», հնարավոր է ընտրել միայն հաղթող թիմին կամ Ոչ ոքի։ Այս ընտրանքը կարող է փոխվել մինչ հեռացման մեկնարկը։ «Գոլեր հաղթանակի համար» ընտրանքը հնարավոր է փոխել մրցաշարի ընթացքում։',
            'form-subheader-names-text':'Այստեղ մուտքագրված հերթականությունը կանդրադառնա աղյուսակում սկզբնական դասավորության վրա։',
            'Names': 'Անուններ',            
            'player-form-duplicate-name': '«{{name}}» անունն արդեն օգտագործվել է։'
        }
    },
    ru: {
        translation: {
            'English': 'English - Английский',
            'Armenian': 'Հայերեն - Армянский',
            'Russian': 'Русский',
            'Home': 'Домой',
            'Settings': 'Настройки',
            'Login': 'Вход',
            'Logout': 'Выход',
            'Login_verb': 'Входите',
            'Save': 'Сохранить',
            'Account': 'Учётная запись',
            'Register': 'Регистрироваться',
            'Register_verb': 'Регистрируйтесь',
            'Next': 'Продолжить',
            'Don\'t have an Account yet?': 'У вас нет учётной записи?',
            'Already have an Account?': 'Уже есть учетная запись?',
            'Confirm': 'Подтвердить',
            'Login to app': 'Войти в {{appName}}',
            'Register for': 'Зарегистрироваться на {{appName}}',
            'Display Name': 'Имя',
            'Email': 'Почта',
            'Password': 'Пароль',
            'Current Password': 'Текущий пароль',
            'New Password': 'Новый пароль',
            'Confirm Password': 'Подтвердите Пароль',
            'Forgot Password?': 'Забыли пароль?',
            'Request new password': 'Сбросить пароль',
            'Google Login': 'Вход через Google',
            'Facebook Login': 'Вход через Facebook',
            'Language': 'Язык',
            'Email is required': 'Электронная почта обязательна',
            'Invalid Email Address': 'Неверный адрес электронной почты',
            'Please enter the Password': 'Введите пароль',
            'Please enter a Password': 'Введите пароль',
            'Please enter a new Password': 'Введите новый пароль',
            'Please confirm the Password': 'Повторно введите пароль',
            'Passwords do not match': 'Пароли не совпадают',
            'Wrong Password': 'Неверный пароль',
            'Registration success': 'Вы успешно зарегистрировались',
            'registration-success-body': 'Вы успешно зарегистрировались. Пожалуйста, проверьте свою электронную почту, чтобы подтвердить свою учетную запись. Если вы не получили письмо, вы можете запросить новое',
            'registration-success-body-end1': ' через {{sec}} сек.',
            'registration-success-body-end2': 'нажимая кнопку ниже.',
            'Resend Verification Email': 'Выслать повторно письмо для подтверждения',
            'Check your Email': 'Праверьте вашу почту',
            'password-reset-success-body': 'Ссылка для сброса пароля была отправлена на ваш адрес электронной почты.',
            'Google Login Error:': 'Ошибка входа Google:',
            'Email Verification': 'Подтверждение электронной почты',
            'email-verification-success': 'Уважаемый {{displayName}}, ваш адрес электронной почты {{email}} успешно подтвержден. Можете войти.',
            'email-verification-success-only-email': 'Ваш адрес электронной почты {{email}} успешно подтвержден. Можете войти.',
            'Go to Login Page': 'На страницу входа',
            'Unknown Error': 'Неизвестная ошибка',
            'Manage Tournaments': 'Управление турнирами',
            'Select Mode': 'Выберите режим',
            'Tournament Settings': 'Настройки турнира',
            'Add Participants': 'Добавьте участников',
            'Create New Tournament': 'Создать новый турнир',
            'Login to Create a Tournament': 'Войдите, чтобы создать турнир',
            'User Profile': 'Профиль',
            'ERROR_EmailInUseError': 'Адрес электронной почты уже используется',
            'ERROR_EmailRequestSmallIntervalError': 'Интервал между новыми запросами электронной почты был слишком мал, попробуйте позже',
            'ERROR_InvalidTokenError': 'Предоставленный токен недействителен',
            'ERROR_AlreadyVerifiedError': 'Пользователь уже подтвержден',
            'ERROR_UserNotFoundError': 'Пользователь не найден',
            'ERROR_WrongPasswordError': 'Неверный пароль',
            'ERROR_UserNotVerifiedError': 'Пользователь не подтвержден',
            'ERROR_ValidationError': 'Ошибка валидации',
            'ERROR_MailSendError': 'Ошибка при отправке письма',
            'ERROR_SocialUserForgotPasswordError': 'Вы не можете сбросить пароль, так как вы вошли в систему через Google / Facebook',
            'Your Profile': 'Ваш профиль',
            'You are logged out': 'Вы вышли из системы',
            'Changes saved': 'Изменения сохранены',            
            'Round Robin': 'Все со всеми',
            'Last Man Standing': 'Последний выживший (LMS)',
            'Elimination': 'На вылет',
            'Number of Tables': 'Количество столов',
            'Quick Entry': 'Быстрый вход',
            'Goals to Win': 'Голы для победы',
            'Draw': 'Ничья',
            'Winning Sets': 'Сеты для победы',
            'Tables': 'Столы',
            'Table': 'стол',
            'Table_plural': 'столов',
            'Table_1': 'стола',
            'Table_2': 'столов',
            'Goals': 'Голы',
            'Goal': 'гол',
            'Goal_plural': 'голов',
            'Goal_1': 'гола',
            'Goal_2': 'голов',
            'Set': '{{count}} сет',
            'Set_plural': '{{count}} сетов',
            'Set_1': '{{count}} сета',
            'Set_2': '{{count}} сетов',
            'form-subheader-tables-text': 'Столы можно добавлять или удалять во время турнира.',
            'form-subheader-goals-text': 'Если выбран «Быстрый вход», вы можете выбрать только победившую команду или ничью. Этот параметр можно изменить перед запуском системы исключения. «Голы на победу» можно менять во время турнира.',
            'form-subheader-names-text':'Очередность заданная здесь отразиться на первоначальном расположении в таблице.',
            'Names': 'Имена',
            'player-form-duplicate-name': 'Имя\'{{name}}\' уже используется!'
        }
    }
}

export default localization;