const localization = {
    en: {
        translation: {
            'English': 'English',
            'Armenian': 'Հայերեն - Armenian',
            'Russian': 'Русский - Russian',
            'Home': 'Home',
            'Settings': 'Settings',
            'Login': 'Login',
            'Login_verb': 'Login',
            'Account': 'Account',
            'Register': 'Register',
            'Register_verb': 'Register',
            'Don\'t have an Account yet?': 'Don\'t have an Account yet?',
            'Already have an Account?': 'Already have an Account?',
            'Confirm': 'Confirm',
            'Login to app': 'Login to {{appName}}',
            'Register for': 'Register for {{appName}}',
            'Display Name': 'Display Name',
            'Email': 'Email',
            'Password': 'Password',
            'Confirm Password': 'Confirm Password',
            'Forgot Password?': 'Forgot Password?',
            'Request new password': 'Request new password',
            'Google Login': 'Google Login',
            'Facebook Login': 'Facebook Login',
            'Language': 'Language',
            'Email is required': 'Email is required',
            'Invalid Email Address': 'Invalid Email Address',
            'Please enter the Password': 'Please enter the Password',
            'Please enter a Password': 'Please enter a Password',
            'Please enter a new Password': 'Please enter a new Password',
            'Please confirm the Password': 'Please confirm the Password',
            'Passwords do not match': 'Passwords do not match',
            'password-validation-error': 'Use at least 8 characters that include Latin lowercase, uppercase letters, and numbers.',
            'Wrong Password': 'Wrong Password',
            'Registration success': 'Registration success',
            'registration-success-body': 'You have successfully registered. Please check your email to verify your account.',
            'Resend Verification Email': 'Resend Verification Email',
            'Check your Email': 'Check your Email',
            'password-reset-success-body1': 'The password reset link has been sent to your email address.',
            'password-reset-success-body2': 'Didn\'t receive the Email? Try sending it again.',
            'Google Login Error:': 'Google Login Error:',
        }
    },
    hy: {
        translation: {
            'English': 'English - Անգլերեն',
            'Armenian': 'Հայերեն',
            'Russian': 'Русский - Ռուսերեն',
            'Home': 'Սկիզբ',
            'Settings': 'Կարգավորումներ',
            'Login': 'Մուտք',
            'Login_verb': 'Մուտք գործեք',
            'Account': 'Հաշիվ',
            'Register': 'Գրանցվել',
            'Register_verb': 'Գրանցվեք',
            'Don\'t have an Account yet?': 'Դեռ չունե՞ք հաշիվ։',
            'Already have an Account?': 'Արդեն գրանցվա՞ծ եք։',
            'Confirm': 'Հաստատել',
            'Login to app': 'Մուտք {{appName}}',
            'Register for': 'Գրանցվեք {{appName}}-ում',
            'Display Name': 'Անուն',
            'Email': 'Էլ. փոստ',
            'Password': 'Գաղտնաբառ',
            'Confirm Password': 'Հաստատեք գաղտնաբառը',
            'Forgot Password?': 'Մոռացե՞լ եք գաղտնաբառը',
            'Request new password': 'Վերակայել գաղտնաբառը',
            'Google Login': 'Մուտք Google-ով',
            'Facebook Login': 'Մուտք Facebook-ով',
            'Language': 'Լեզու',
            'Email is required': 'Էլ. փոստը պարտադիր է',
            'Invalid Email Address': 'Անվավեր էլ. փոստի հասցե',
            'Please enter the Password': 'Մուտքագրեք գաղտնաբառը',
            'Please enter a Password': 'Մուտքագրեք գաղտնաբառ',
            'Please enter a new Password': 'Մուտքագրեք նոր գաղտնաբառ',
            'Please confirm the Password': 'Կրկնեք գաղտնաբառը',
            'Passwords do not match': 'Գաղնտաբառերը չեն համընկնում',
            'password-validation-error': 'Գաղտնաբառը պետք է կազմված լինի առնվազն 8 նիշից և պարունակի լատինական այբուբենի մեծատառեր, փոքրատառեր և թվեր։',
            'Wrong Password': 'Գաղտնաբառը սխալ է',
            'Registration success': 'Գրանցումը հանջողվեց',
            'registration-success-body': 'Դուք հաջողությամբ գրանցվել եք։ Խնդրում ենք ստուգել Ձեր էլ. փոստը, որպեսզի հաստատեք Ձեր հաշիվը։',
            'Resend Verification Email': 'Նորից ուղարկել հաստատման նամակը',
            'Check your Email': 'Ստուգեք Ձեր էլ. փոստը',
            'password-reset-success-body1': 'Գաղտնաբառի վերակայման հղումն ուղարկվել է Ձեր էլ. փոստի հասցեին։',
            'password-reset-success-body2': 'Չե՞ք ստացել նամակը։ Փորձեք ուղարկել այն նորից։',
            'Google Login Error:': 'Google մուտքի սխալ.',
        }
    },
    ru: {
        translation: {
            'English': 'English - Английский',
            'Armenian': 'Հայերեն - Армянский',
            'Russian': 'Русский',
            'Home': 'Домой',
            'Settings': 'Настройки',
            'Login': 'Вход',
            'Login_verb': 'Входите',
            'Account': 'Учётная запись',
            'Register': 'Регистрироваться',
            'Register_verb': 'Регистрируйтесь',            
            'Don\'t have an Account yet?': 'У вас нет учётной записи?',
            'Already have an Account?': 'Уже есть учетная запись?',
            'Confirm': 'Подтвердить',
            'Login to app': 'Войти в {{appName}}',
            'Register for': 'Зарегистрироваться на {{appName}}',
            'Display Name': 'Имя',
            'Email': 'Почта',
            'Password': 'Пароль',
            'Confirm Password': 'Подтвердите Пароль',
            'Forgot Password?': 'Забыли пароль?',
            'Request new password': 'Сбросить пароль',
            'Google Login': 'Вход через Google',
            'Facebook Login': 'Вход через Facebook',
            'Language': 'Язык',
            'Email is required': 'Электронная почта обязательна',
            'Invalid Email Address': 'Неверный адрес электронной почты',
            'Please enter the Password': 'Введите пароль',
            'Please enter a Password': 'Введите пароль',
            'Please enter a new Password': 'Введите новый пароль',
            'Please confirm the Password': 'Повторно введите пароль',
            'Passwords do not match': 'Пароли не совпадают',
            'Wrong Password': 'Неверный пароль',
            'Registration success': 'Вы успешно зарегистрировались',
            'registration-success-body': 'Вы успешно зарегистрировались. Пожалуйста, проверьте свою электронную почту, чтобы подтвердить свою учетную запись.',
            'Resend Verification Email': 'Выслать повторно письмо для подтверждения',
            'Check your Email': 'Праверьте вашу почту',
            'password-reset-success-body1': 'Ссылка для сброса пароля была отправлена на ваш адрес электронной почты.',
            'password-reset-success-body2': 'Не получили письмо? Попробуйте отправить снова.',
            'Google Login Error:': 'Ошибка входа Google:',
        }
    }
}

export default localization;